### ISSUE TITLE
the readme.md seem need to add OMR_INSTALL_LIB_DIR in build instruction?

### ISSUE THREAD

**Issue by jiamo** [dibyendumajumdar/nj#6]
Otherwise it will generate `/cmake/Omr` in cmake_install.cmake  which it is a root path dir.

**Comment by dibyendumajumdar** [comment]
@jiamo thank you. I will check.

**Comment by dibyendumajumdar** [comment]
Indeed you are correct.

**Comment by dibyendumajumdar** [comment]
It looks like some stuff crept in when I merged OMR changes. To be honest we do not need this so I have commented it out. I tested on Windows where of course the /cmake/Omr folder got created no problem :-(

**Comment by dibyendumajumdar** [comment]
this is fixed
